name: CI - Static Checks

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  pre-commit:
    name: Pre-commit Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: j178/prek-action@d607fccab750f3fa1b4dbc347eec8765a50bf9d2 # v1
